global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'saga-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['saga:8082']

rule_files:
  - "alert.rules.yml"
